export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOG_IN_START = 'LOG_IN_START'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

export const LOG_OUT = 'LOG_OUT'

export const CREATE_ENTRY = 'CREATE_ENTRY'
export const UPDATE_ENTRY = 'UPDATE_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY'

export const SEARCH_FOOD = 'SEARCH_FOOD'
export const SEARCHING_FOOD = 'SEARCHING_FOOD'

export const FETCH_GOAL = 'FETCH_GOAL'
export const SAVE_GOAL = 'SAVE_GOAL'


export const FETCH_LOGS = 'FETCH_LOGS'
export const FETCH_LOG_START = 'FETCH_LOG_START'
export const FETCH_LOG_SUCCESS = 'FETCH_LOG_SUCCESS'
export const SELECT_DAY = 'SELECT_DAY'




export const CREATE_ENTRY_START = 'CREATE_ENTRY_START'
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS'
export const CREATE_ENTRY_FAILURE = 'CREATE_ENTRY_FAILURE'

export const UPDATE_ENTRY_START = 'UPDATE_ENTRY_START'
export const UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS'
export const UPDATE_ENTRY_FAILURE = 'UPDATE_ENTRY_FAILURE'
