export const SIGN_UP = 'SIGN_UP'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const CREATE_ENTRY = 'CREATE_ENTRY'
export const UPDATE_ENTRY = 'UPDATE_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY'
export const FETCH_LOG = 'FETCH_LOG'
export const SEARCH_FOOD = 'SEARCH_FOOD'
